version: '3.8'
services:
  mongodb_email:
    image: mongo
    container_name: mongodb-email
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
