spring:
  data:
    mongodb:
      host: localhost
      port: 27019
      authentication-database: admin
      username: root
      password: pass
      database: emails_db
  application:
    name: email-api
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
        test-connection: true
    host: smtp.gmail.com
    port: 587
    username: email.webiii@gmail.com
    password: ihxykrzkfyoipyhb

#password.webIII.@123


server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

