spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      authentication-database: admin
      username: root
      password: pass
      database: pedidos_db
  application:
    name: pedido-api

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/