version: '3.8'
services:
  mongodb_catalogo:
    image: mongo
    container_name: mongodb-catalogo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


volumes:
  mongodb-data:
