version: '3.8'
services:
  mongodb_pedido:
    image: mongo
    container_name: mongodb-pedido
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

